-- `social_link` always held a profile URL and is now presented as LinkedIn. Renamed in place
-- instead of the drop+add Prisma generated by default, so any existing values survive the
-- migration rather than being silently discarded.
ALTER TABLE "team_members" RENAME COLUMN "social_link" TO "linkedin_url";

-- AlterTable
ALTER TABLE "team_members"
ADD COLUMN     "department" TEXT,
ADD COLUMN     "email" TEXT,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "responsibilities" TEXT NOT NULL DEFAULT '';

-- CreateTable
CREATE TABLE "about_company_team_section" (
    "id" TEXT NOT NULL,
    "eyebrow" TEXT NOT NULL DEFAULT 'Meet the Team',
    "heading" TEXT NOT NULL DEFAULT 'The People Behind PPN',
    "description" TEXT NOT NULL DEFAULT '',
    "cta_label" TEXT,
    "cta_href" TEXT,
    "show_counter" BOOLEAN NOT NULL DEFAULT false,
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "translations" JSONB,

    CONSTRAINT "about_company_team_section_pkey" PRIMARY KEY ("id")
);
